<?php
namespace Modules\Course\Models;

use App\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sections extends BaseModel
{
    use SoftDeletes;
    protected $table = 'bravo_course_section';
    protected $fillable = ['name', 'display_type', 'hide_in_single', 'course_id','active'];
    protected $slugField = 'slug';
    protected $slugFromField = 'name';

    public function lessons()
    {
        return $this->hasMany(Lessons::class, 'section_id', 'id')->orderBy("display_order", "asc")->with(['translations']);
    }
    public function frontendLessons(){
        return $this->hasMany(Lessons::class,'section_id','id')->where('active',1)->orderBy('display_order','ASC');
    }

    public function course()
    {
        return $this->hasOne("Modules\Course\Models\Course", "id" , "course_id");
    }

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ( $this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }

    public function getLessonsStudyJsDataAttribute(){
        $res = [];
        foreach($this->frontendLessons as $module){

            $res[] = [
                'id'=>$module->id,
                'title'=>$module->name,
                'study_url'=>$module->study_url,
                'duration_html'=>$module->duration_html
            ];
        }
        return $res;
    }
}
